exit if cache update fails

diff --git a/upgrade-status b/upgrade-status
--- a/upgrade-status
+++ b/upgrade-status
@@ -10,7 +10,7 @@ if [ -f /etc/redhat-release ]; then
     fi
 
     # get number of updates
-    sudo dnf -qy makecache || echo "Error: Unable to update dnf repositories"
+    sudo dnf -qy makecache || { echo "Error: Unable to update dnf repositories"; exit 1; }
     updates=$(sudo dnf updateinfo list -q | awk -F " " '{print $NF}' | wc -l)
 
 # debian
@@ -23,7 +23,7 @@ elif [ -f /etc/debian_version ]; then
     fi
 
     # get number of updates
-    sudo apt-get -qq update || echo "Error: Unable to update apt repositories"
+    sudo apt-get -qq update || { echo "Error: Unable to update apt repositories"; exit 1; }
     updates=$(sudo apt-get -qq -y --ignore-hold --allow-change-held-packages --allow-unauthenticated -s dist-upgrade | grep ^Inst | wc -l)
 
 # unknown os
